### ISSUE TITLE
Sope install issues

### ISSUE THREAD

**Issue by deadmanrod** [ethoms/freebsd-ports#2]
Just downloaded and installing on a virgin BSD 10.1 received the following:

====> Compressing man pages (compress-man)
===>   Installing ldconfig configuration file
===>  Installing for sope-2.2.14
===>  Checking if sope already installed
===>   Registering installation for sope-2.2.14
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/EOQualifier+LDAP.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdap.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapAttribute.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapConnection.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapDataSource.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapEntry.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapFileManager.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapGlobalID.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapModification.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapSearchResultEnumerator.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NGLdapURL.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Headers/NGLdap/NSString+DN.h: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Libraries/libNGLdap.so: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Libraries/libNGLdap.so.4.9: No such file or directory
pkg-static: Unable to access file /usr/ports/devel/sope/work/stage/usr/local/GNUstep/Local/Library/Libraries/libNGLdap.so.4.9.35: No such file or directory
**\* Error code 74

Stop.
make[1]: stopped in /usr/ports/devel/sope
**\* Error code 1

Stop.
make: stopped in /usr/ports/devel/sope

**Comment by ethoms** [comment]
I'll look into this as soon as I can get time. It did built perfectly fine last time I tried on FreeBSD 10.1p9. Perhaps some ports tree changes have broken the port. Please specify the port options used, and any other details I may find useful to reproduce your issue.

**Comment by ethoms** [comment]
I'm closing this issue  as this is out of date. It must be resolved by further developments.
