### ISSUE TITLE
SOGo-Apache.conf needs patch

### ISSUE THREAD

**Issue by niklaas** [ethoms/freebsd-ports#4]
(Since I installed SOGo successfully some days ago, I would like to submit some issues I encountered. I intend to submit patches for them by myself as soon as I have time to do so.)

The SOGo-Apache.conf provided refers to wrong directories. See below the original .conf and my changes to make it work.

```
#Alias /SOGo.woa/WebServerResources/ \
#      /usr/lib/GNUstep/SOGo/WebServerResources/
#Alias /SOGo/WebServerResources/ \
#      /usr/lib/GNUstep/SOGo/WebServerResources/

Alias /SOGo.woa/WebServerResources/ \
      /usr/local/GNUstep/Local/Library/SOGo/WebServerResources/
Alias /SOGo/WebServerResources/ \
      /usr/local/GNUstep/Local/Library/SOGo/WebServerResources/

##<Directory /usr/lib/GNUstep/SOGo/>
<Directory /usr/local/GNUstep/Local/Library/SOGo/>
--------------8<--------------------------------------
```

**Comment by ethoms** [comment]
I think you are correct, the path in the port version is probably for Linux distros. I just copied the file from the SOGo source tarball. Since i use Nginx, I didn't test it. I will create an update for it soon.

Thanks for pointing this out.
