### ISSUE TITLE
MySQL as backend seems not to work

### ISSUE THREAD

**Issue by niklaas** [ethoms/freebsd-ports#5]
When trying to use MySQL as backend, I get the following error:

```
2016-01-24 23:20:30.461 sogod[78721:101751] EOAdaptor: cannot find adaptor bundle: 'MySQL'
Jan 24 23:20:30 sogod [78721]: [ERROR] <0x0x80ceec190[WOWatchDog]> an exception occured in runloop <NSException: 0x80e719560> NAME:NSInvalidArgumentException REASON:Tried to add nil value for key 'sql.sogo.domain.tld:5432:sogo:sogo' to dictionary INFO:{}
```

I haven't investigated this in depth but I assume that the port misses something in relation to the MySQL backend. I switched to PostgreSQL (which works fine) but probably one should take a closer look on this.

**Comment by dingensdongens** [comment]
MySQL support would be great!

**Comment by ethoms** [comment]
Firstly, the www/sogo port is in the official ports tree. Are you using it from there or from this github project? Please use it from an up to date official ports tree.

The mysql support is provided by the dependency port devel/sope. You must select MYSQL from the "make config" options. I'm fairly sure others have reported success with mysql and SOGo.

If you have already done the above steps and still have a problem, please create a PR on the FreeBSD bugzilla, filing it as a ports issue and giving www/sogo or devel/sope in the title of the PR. This github project is only for my development use or new ports that are not yet approved into the official ports tree.

**Comment by niklaas** [comment]
Ok. I'll re-check and, if necessary, file the bug as soon as I can on FreeBSD's bugzilla.

Maybe, if possible, you should disable the »issues« feature for the repo here on github.
