### ISSUE TITLE
Add information about memcached in pkg-message

### ISSUE THREAD

**Issue by niklaas** [ethoms/freebsd-ports#6]
Probably we should add some information about how to properly configure `memcached` to work with SOGo. This would spare beginners some time.

**Comment by ethoms** [comment]
That would be great. Please create a PR on the FreeBSD bugzilla and attach a patch for the pkg-message. I will review and approve it as sson as I can. If it's done soon, it may go into the same update as the Apache conf issue you raised.

What configuration are you referring to? I just install and run memcached on the same host and then set "SOGoMemcachedHost" to the host IP in my sogo.conf. It's quite straight forward. With SOGo, the end user will have to read the SOGo Installation Guide, it's not feasible to include configuration instructions for software as complex or agnostic as SOGo. Note that memcached could be installed on another host/jail.

**Comment by niklaas** [comment]
Same here. I'll continue communicating this via the official FreeBSD bugzilla, as soon as I can.
