### ISSUE TITLE
When you think that will be available sogo3?

### ISSUE THREAD

**Issue by hedon77** [ethoms/freebsd-ports#7]
Hi,

When you think that will be available sogo3?

Best regards

**Comment by dingensdongens** [comment]
Also desperately waiting for sogo3 port. Currently only the 2.x release is in the ports tree. But we can't step down from modern UI (e.g. roundcube) to an "old-fashioned" webmailer. Please port sogo3 to FreeBSD. Thanks a lot for all your efforts!

Btw: What about openchange is it part of the samba4 port? Why is it called libmapi and not openchange? Is the setup the same?

**Comment by ethoms** [comment]
Regarding SOGo v3, I will work on a port when I get time. I've been very busy lately with some of my own open source projects: https://github.com/ethoms/netdrive-connector and https://github.com/ethoms/django-djaken . I'm finished working on those for a while, but nned to catach up on other things before I start work on v3. Keep checking back here and the bugzilla for progress. It's not likely to be for another week or so, unless somebody else works on it.

I don't know anything about openchange, and don't have any plans to use it or make a port for it. Feel free to try yourselves, or request on some of the relevant channels (the Ports mailing list, FreeBSD forum, Wanted Ports). Sorry I can't help with that one.
