### ISSUE TITLE
ejabberd PR

### ISSUE THREAD

**Issue by Neustradamus** [ethoms/freebsd-ports#8]
Hello Euan,

Sorry for this place but after some months, an email, a second email and one year after, I contact you again here about ejabberd.

Can you look your PR? (PR 2344)

The main problem is that you have not sign the CLA.

Can you sign the CLA?
If you have already done please specify in the ticket?
If not, can you do it and inform in the ticket?

Update your code to last ejabberd version?

Thanks in advance.

Regards,

Neustradamus

Linked to: https://github.com/ethoms/raspi-hacks/issues/1

**Comment by ethoms** [comment]
Closing issue, as not related to this project.

**Comment by Neustradamus** [comment]
Thanks for your comeback in the ejabberd repository :)
